-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 16:12:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_instrument
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet_instrument
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_instrument` DEFAULT CHARACTER SET utf8mb4 ;
USE `projet_instrument` ;

-- -----------------------------------------------------
-- Table `projet_instrument`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_instrument`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img_url` TEXT(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_instrument`.`instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_instrument`.`instruments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `resume` VARCHAR(500) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `son` VARCHAR(255) NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_instruments_image1_idx` (`image_id` ASC) VISIBLE,
  CONSTRAINT `fk_instruments_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `projet_instrument`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_instrument`.`musiciens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_instrument`.`musiciens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_musicien` VARCHAR(255) NOT NULL,
  `prenom_musicien` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_instrument`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_instrument`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_categorie` VARCHAR(255) NOT NULL,
  `description_categorie` TEXT(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_instrument`.`instruments_has_musiciens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_instrument`.`instruments_has_musiciens` (
  `instruments_id` INT NOT NULL,
  `musiciens_id` INT NOT NULL,
  PRIMARY KEY (`instruments_id`, `musiciens_id`),
  INDEX `fk_instruments_has_musiciens_musiciens1_idx` (`musiciens_id` ASC) VISIBLE,
  INDEX `fk_instruments_has_musiciens_instruments_idx` (`instruments_id` ASC) VISIBLE,
  CONSTRAINT `fk_instruments_has_musiciens_instruments`
    FOREIGN KEY (`instruments_id`)
    REFERENCES `projet_instrument`.`instruments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instruments_has_musiciens_musiciens1`
    FOREIGN KEY (`musiciens_id`)
    REFERENCES `projet_instrument`.`musiciens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_instrument`.`instruments_has_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_instrument`.`instruments_has_categorie` (
  `instruments_id` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  PRIMARY KEY (`instruments_id`, `categorie_id`),
  INDEX `fk_instruments_has_categorie_categorie1_idx` (`categorie_id` ASC) VISIBLE,
  INDEX `fk_instruments_has_categorie_instruments1_idx` (`instruments_id` ASC) VISIBLE,
  CONSTRAINT `fk_instruments_has_categorie_instruments1`
    FOREIGN KEY (`instruments_id`)
    REFERENCES `projet_instrument`.`instruments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instruments_has_categorie_categorie1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `projet_instrument`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_instrument`.`musiciens_has_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_instrument`.`musiciens_has_categorie` (
  `musiciens_id` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  PRIMARY KEY (`musiciens_id`, `categorie_id`),
  INDEX `fk_musiciens_has_categorie_categorie1_idx` (`categorie_id` ASC) VISIBLE,
  INDEX `fk_musiciens_has_categorie_musiciens1_idx` (`musiciens_id` ASC) VISIBLE,
  CONSTRAINT `fk_musiciens_has_categorie_musiciens1`
    FOREIGN KEY (`musiciens_id`)
    REFERENCES `projet_instrument`.`musiciens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musiciens_has_categorie_categorie1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `projet_instrument`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
